service: madcamp3

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2

functions:
  asdf:
    handler: src/handler.asdf
    events:
      - http:
          path: asdf
          method: get
  connectHandler:
    handler: src/handler.connectHandler
    events:
      - websocket: $connect

  disconnectHandler:
    handler: src/handler.disconnectHandler
    events:
      - websocket: $disconnect

  login:
    handler: src/login.kakao
    events:
      - http:
          path: oauth
          method: get

  offerHandler:
    handler: src/handler.offerHandler
    events:
      - websocket:
          route: offer

  answerHandler:
    handler: src/handler.answerHandler
    events:
      - websocket:
          route: answer

package:
  exclude:
    - node_modules/**
    - test/**
    - src/**/*.spec.ts
    - src/**/*.test.ts

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
