service: madcamp3

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  connectHandler:
    handler: src/handler.connectHandler
    events:
      - websocket: $connect

  disconnectHandler:
    handler: src/handler.disconnectHandler
    events:
      - websocket: $disconnect

  offerHandler:
    handler: src/handler.offerHandler
    events:
      - websocket:
          route: offer
          authorizer: aws_iam

  answerHandler:
    handler: src/handler.answerHandler
    events:
      - websocket:
          route: answer
          authorizer: aws_iam

plugins:
  - serverless-webpack

package:
  exclude:
    - node_modules/**
    - test/**
    - src/**/*.spec.ts
    - src/**/*.test.ts

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
