service: madcamp3

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    DB_HOST: env:DB_HOST
    DB_USER: env:DB_USER
    DB_PASSWORD: env:DB_PASSWORD
    DB_DATABASE: env:DB_DATABASE
    KAKAO_API_KEY: env:KAKAO_API_KEY
    KAKAO_REDIRECT_URI: env:KAKAO_REDIRECT_URI
#  vpc:
#    securityGroupIds:
#      - sg-03c8f44df5d0ba5e8
#    subnetIds:
#      - subnet-021c9f3243ce5e7e4
#      - subnet-02b46346a9cd6d05f
#      - subnet-06faacce00843a1e1
#      - subnet-09556e818e3f5e2a7
#  iam:
#    role: arn:aws:iam::730335448938:role/lambda-rds




functions:
  asdf:
    handler: src/handler.asdf
    events:
      - http:
          path: asdf
          method: get
  connectHandler:
    handler: src/handler.connectHandler
    events:
      - websocket: $connect

  disconnectHandler:
    handler: src/handler.disconnectHandler
    events:
      - websocket: $disconnect

  login:
    handler: src/login.kakao
    events:
      - http:
          path: oauth
          method: get

  offerHandler:
    handler: src/handler.offerHandler
    events:
      - websocket:
          route: offer

  answerHandler:
    handler: src/handler.answerHandler
    events:
      - websocket:
          route: answer

package:
  exclude:
    - node_modules/**
    - test/**
    - src/**/*.spec.ts
    - src/**/*.test.ts



custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dotenv:
    basePath: ./
