name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          DB_HOST: ${{ secrets.DB_HOST }} >> .env
          DB_USER: ${{ secrets.DB_USER }} >> .env
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} >> .env
          DB_DATABASE: ${{ secrets.DB_DATABASE }} >> .env
          KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }} >> .env
          KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }} >> .env
        run: npx serverless deploy
